<?php

/**
 * @file
 * Contains my_maps.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function my_maps_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the my_maps module.
    case 'help.page.my_maps':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom code for maps') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function my_maps_theme() {
  return [
    'my_maps' => [
      'template' => 'my_maps',
      'render element' => 'children',
    ],
  ];
}
